os: windows

language: node_js
node_js:
  "8"

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn test

deploy:
  - provider: script
    script: echo //registry.npmjs.org/:_authToken=%NPM_TOKEN% > .npmrc && npm publish . && del .npmrc
    on:
      tags: true