image: Visual Studio 2017

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

test_script:
  - yarn lint
  - yarn build
  - yarn test

build: off

deploy:
- provider: Script
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

deploy_script:
  - echo //registry.npmjs.org/:_authToken=%NPM_TOKEN% > .npmrc
  - npm publish .
  - del .npmrc
