image: Visual Studio 2017

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

test_script:
  - yarn lint
  - yarn build
  - yarn test
  - powershell deploy.ps1

build: off
