image: Visual Studio 2017

environment:
  nodejs_version: "8"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - yarn install
  - yarn --version

build_script:
  - yarn lint
  - yarn test
  - yarn build

test: off