image: Visual Studio 2017

environment:
  nodejs_version: "8"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install

before_test:
- node --version
- yarn --version

test_script:
  - yarn lint
  - yarn test
  - yarn build

build:
  on:
    APPVEYOR_REPO_TAG: true

build_script:
  - echo //registry.npmjs.org/:_authToken=%NPM_TOKEN% > .npmrc
  - npm publish .

after_build:
  - del .npmrc
