image: Visual Studio 2017

environment:
  nodejs_version: "8"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install

before_test:
- node --version
- yarn --version

test_script:
  - yarn lint
  - yarn test

build_script:
  - yarn build

deploy:
  - on:
    APPVEYOR_REPO_TAG: true

deploy_script:
  - echo //registry.npmjs.org/:_authToken=%NPM_TOKEN% > .npmrc
  - npm publish .

after_deploy:
  - del .npmrc
